apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-05T17:18:13Z"
  generation: 3
  labels:
    app: py-sum-api
  name: py-sum-api
  namespace: noether
  resourceVersion: "2156"
  uid: 1943a0dc-b74f-4084-9681-9bafcc347228
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: py-sum-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: py-sum-api
    spec:
      containers:
      - image: sum-api:v1.0.0
        imagePullPolicy: IfNotPresent
        name: sum-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-05T17:18:13Z"
    lastUpdateTime: "2023-06-05T17:22:27Z"
    message: ReplicaSet "py-sum-api-5779b44f4b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-05T17:36:47Z"
    lastUpdateTime: "2023-06-05T17:36:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
