apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py-sum-api
  name: py-sum-api
  namespace: noether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-sum-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: py-sum-api
    spec:
      containers:
      - image: sum-api:v1.0.0
        name: sum-api
        resources: {}
status: {}
